PREFIX owl:    <http://www.w3.org/2002/07/owl#>
PREFIX base:   <http://opencaesar.io/formal-methods-wg-example/vocabulary/base#>

SELECT ?iri ?pred ?obj
FROM <http://opencaesar.io/formal-methods-wg-example/description/router>

WHERE {
	?iri a owl:NamedIndividual ;
		?pred ?obj .
}
ORDER BY ?iri ?pred
